// Daily deck publishing, shared by the server's built-in scheduler and the
// manual CLI (scripts/generate-daily-deck.js).
//
// Content source, in order: Gemini (when GEMINI_API_KEY is set) → yesterday's
// deck (spec: "failure mode = serve yesterday's deck") → the sampleDeck in
// the experiment config. Publishing never fails, so POOL_MISSING can only
// mean "not generated yet", never "generation broke".
//
// Concurrency: an advisory transaction lock keyed on the day serializes
// simultaneous publishes from any number of pods; the existence check inside
// the lock makes re-runs no-ops.
import { query, withTx } from './db.js';
import { todayKey, nextDayKey, nextResetAt } from './day.js';
import { geminiEnabled, generateDeckWithGemini } from './gemini.js';

async function fetchRecentTitles(cfg, day) {
  const { rows } = await query(
    `SELECT DISTINCT title FROM deck_cards
      WHERE day < $1 AND day >= ($1::date - $2::int)`,
    [day, cfg.deck.recentTitleDays],
  );
  return rows.map((r) => r.title);
}

// Latest published deck before `day` — the "stale beats broken" fallback.
async function fetchPreviousDeck(day) {
  const { rows } = await query(
    'SELECT day FROM deck_days WHERE day < $1 ORDER BY day DESC LIMIT 1',
    [day],
  );
  if (rows.length === 0) return null;
  const prevDay = rows[0].day;
  const { rows: cards } = await query(
    `SELECT title, art_key, theme, fortune, finding, consult_nudge, prefill_question
       FROM deck_cards WHERE day = $1 ORDER BY card_id`,
    [prevDay],
  );
  return cards.length ? cards : null;
}

async function generateDeck(cfg, day) {
  if (geminiEnabled()) {
    try {
      const recentTitles = await fetchRecentTitles(cfg, day);
      const deck = await generateDeckWithGemini(cfg, day, recentTitles);
      console.log(`[deck] ${day}: content generated by Gemini (${deck.length} cards)`);
      return deck;
    } catch (err) {
      console.error(`[deck] ${day}: Gemini generation failed (${err.message}) — falling back`);
      const previous = await fetchPreviousDeck(day);
      if (previous) {
        console.log(`[deck] ${day}: re-serving previous day's deck (${previous.length} cards)`);
        return previous;
      }
    }
  } else {
    console.log(`[deck] ${day}: GEMINI_API_KEY not set — using config sample deck`);
  }
  return cfg.sampleDeck;
}

export async function publishDeck(cfg, day, { force = false } = {}) {
  // Generate BEFORE opening the transaction — Gemini can take many seconds
  // and must not hold DB locks while it thinks.
  const deck = await generateDeck(cfg, day);

  return withTx(async (client) => {
    await client.query('SELECT pg_advisory_xact_lock(hashtext($1))', [`bhagya-deck-${day}`]);

    const existing = await client.query('SELECT 1 FROM deck_days WHERE day = $1', [day]);
    if (existing.rowCount > 0) {
      if (!force) return { published: false, reason: 'exists' };
      const used = await client.query(
        'SELECT count(*)::int AS n FROM user_daily_draws WHERE day = $1',
        [day],
      );
      if (used.rows[0].n > 0) {
        throw new Error(
          `refusing --force: ${used.rows[0].n} user(s) already drew on ${day}; replacing the deck would break their stable card`,
        );
      }
      await client.query('DELETE FROM deck_days WHERE day = $1', [day]);
      console.log(`[deck] --force: replaced existing (unused) deck for ${day}`);
    }

    await client.query('INSERT INTO deck_days (day) VALUES ($1)', [day]);
    for (let i = 0; i < deck.length; i++) {
      const card = deck[i];
      await client.query(
        `INSERT INTO deck_cards
           (day, card_id, title, art_key, theme, fortune, finding, consult_nudge, prefill_question)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
        [
          day, i + 1, card.title, card.art_key, card.theme,
          JSON.stringify(card.fortune), card.finding, card.consult_nudge, card.prefill_question,
        ],
      );
    }

    console.log(`[deck] published deck for ${day}: ${deck.length} cards`);
    return { published: true, total: deck.length };
  });
}

// Cheap idempotent guard used by the server: after the first success for a
// given day it costs nothing (in-memory check); at the 06:00 IST rollover it
// publishes the new day's deck exactly once even under concurrent callers.
let ensuredDay = null;
let inflight = null;

export async function ensureDeckForToday(cfg) {
  const day = todayKey();
  if (ensuredDay === day) return day;
  if (!inflight) {
    inflight = (async () => {
      const { rows } = await query('SELECT 1 FROM deck_days WHERE day = $1', [day]);
      if (rows.length === 0) await publishDeck(cfg, day);
      ensuredDay = day;
    })().finally(() => { inflight = null; });
  }
  await inflight;
  return day;
}

// Nightly pre-generation: within DECK_PREGEN_HOURS of the 06:00 IST cutover
// (i.e. during the night), publish TOMORROW's deck ahead of time, so the
// cutover flips onto content that already exists instead of making the first
// 06:00 visitor wait on a Gemini call. Same advisory lock + existence check
// as any publish, so any number of pods can run this concurrently.
const PREGEN_WINDOW_MS = Number(process.env.DECK_PREGEN_HOURS ?? 4) * 3_600_000;
let pregeneratedDay = null;

export async function ensureUpcomingDeck(cfg) {
  if (!(PREGEN_WINDOW_MS > 0)) return null;
  const now = new Date();
  if (nextResetAt(now).getTime() - now.getTime() > PREGEN_WINDOW_MS) return null;
  const day = nextDayKey(todayKey(now));
  if (pregeneratedDay === day) return day;
  const { rows } = await query('SELECT 1 FROM deck_days WHERE day = $1', [day]);
  if (rows.length === 0) {
    console.log(`[deck] nightly pre-generation for ${day}`);
    await publishDeck(cfg, day);
  }
  pregeneratedDay = day;
  return day;
}
